version: '3.8'
services:
  # database section
  
  #payment: postgres
  paymentdb:
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123Pa$$$$word!"
      POSTGRES_DB: PaymentDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
        
  # infrastructure section
  
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=9277.dev@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123Pa$$$$word!
    restart: always
    ports:
      - "5050:80"
        
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
        
  elasticsearch:
    container_name: elasticsearch
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  
  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
        
  payment.api:
    container_name: payment.api
    environment:
      - ASPNET_ENVIRONMENT=Development
      - ASPNET_CORE_URLS=http://+80
      - "ConnectionStrings:DefaultConnectionString=Server=paymentdb;Port=5432;Database=PaymentDb;User Id=postgres;Password=123Pa$$$$word!;"
    depends_on:
      - paymentdb
    ports:
      - "6003:80"
    restart: always